djangopypi2/apps/pypi_packages/urls.py
from django.conf.urls import patterns, include, url
from .feeds import ReleaseFeed
from . import package_views
from . import release_views

PACKAGE = r'(?P<package_name>[\w\d_\.\-]+)'
VERSION = r'(?P<version>[\w\d_\.\-]+)'
USERNAME = r'(?P<username>[\w\d_.@+-]+)'

urlpatterns = patterns('',
    url(r'^rss/$'     , ReleaseFeed(), name='djangopypi2-rss'),
    url(r'^packages/$', package_views.Index.as_view(), name='djangopypi2-packages-index'),
    url(r'^packages/search/$', package_views.advanced_search, name='djangopypi2-packages-search'),

    url(r'^packages/' + PACKAGE + '/$'       , package_views.PackageDetails.as_view(), name='djangopypi2-package'),
    url(r'^packages/' + PACKAGE + '/delete/$', package_views.DeletePackage.as_view(), name='djangopypi2-package-delete'),

    url(r'^packages/' + PACKAGE + '/permission/$', package_views.PackagePermission.as_view(), name='djangopypi2-package-permission'),

    url(r'^packages/' + PACKAGE + '/' + VERSION + '/$'              , release_views.ReleaseDetails.as_view(), name='djangopypi2-release'),
    url(r'^packages/' + PACKAGE + '/' + VERSION + '/delete/$'       , release_views.DeleteRelease.as_view(), name='djangopypi2-release-delete'),
    url(r'^packages/' + PACKAGE + '/' + VERSION + '/edit-details/$' , release_views.ManageRelease.as_view(), name='djangopypi2-release-edit-details'),
    url(r'^packages/' + PACKAGE + '/' + VERSION + '/edit-metadata/$', release_views.manage_metadata, name='djangopypi2-release-edit-metadata'),
    url(r'^packages/' + PACKAGE + '/' + VERSION + '/files/$'        , release_views.manage_files, name='djangopypi2-release-manage-files'),
    url(r'^packages/' + PACKAGE + '/' + VERSION + '/files/upload/$' , release_views.upload_file, name='djangopypi2-release-upload-file'),
)

djangopypi2/apps/pypi_packages/models.py
import os
import json
from logging import getLogger

from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete
from django.db.models.query import Q
from django.utils.translation import ugettext_lazy as _
from django.utils.datastructures import MultiValueDict
from django.contrib.auth.models import User
from django.dispatch import receiver

from ..pypi_metadata.models import Classifier, ClassifierSerializer
from ..pypi_metadata.models import DistributionType
from ..pypi_metadata.models import PythonVersion
from ..pypi_metadata.models import PlatformName

log = getLogger(__name__)

class ConfigurationManager(models.Manager):
    def latest(self):
        try:
            return super(ConfigurationManager, self).latest()
        except Configuration.DoesNotExist:
            configuration = Configuration()
            configuration.save()
            return configuration

class Configuration(models.Model):
    '''Stores the configuration of this site. As a rule, the most
    recent configuration is always used, and past configurations
    are kept for reference and for rollback.
    '''
    objects = ConfigurationManager()

    timestamp = models.DateTimeField(auto_now_add=True)
    allow_version_overwrite = models.BooleanField(default=False)
    upload_directory = models.CharField(max_length=256, default='dists',
        help_text='Direcory relative to MEDIA_ROOT in which user uploads are kept')

    class Meta:
        ordering = ('-timestamp', )
        verbose_name = _(u'Configuration')
        verbose_name_plural = _(u'Configurations')
        get_latest_by = 'timestamp'

class PackageInfoField(models.Field):
    description = u'Python Package Information Field'
    __metaclass__ = models.SubfieldBase

    def __init__(self, *args, **kwargs):
        kwargs['editable'] = False
        super(PackageInfoField,self).__init__(*args, **kwargs)

    def to_python(self, value):
        if isinstance(value, basestring):
            if value:
                return MultiValueDict(json.loads(value))
            else:
                return MultiValueDict()
        if isinstance(value, dict):
            return MultiValueDict(value)
        if isinstance(value, MultiValueDict):
            return value
        raise ValueError('Unexpected value encountered when converting data to python')

    def get_prep_value(self, value):
        if isinstance(value, MultiValueDict):
            return json.dumps(dict(value.iterlists()), default = ClassifierSerializer)
        if isinstance(value, dict):
            return json.dumps(value)
        if isinstance(value, basestring) or value is None:
            return value

        raise ValueError('Unexpected value encountered when preparing for database')

    def get_internal_type(self):
        return 'TextField'

class Package(models.Model):
    name = models.CharField(max_length=255, unique=True, primary_key=True,
                            editable=False)
    auto_hide = models.BooleanField(default=True, blank=False)
    allow_comments = models.BooleanField(default=True, blank=False)
    owners = models.ManyToManyField(User, blank=True,
                                    related_name="packages_owned")
    maintainers = models.ManyToManyField(User, blank=True,
                                         related_name="packages_maintained")

    class Meta:
        verbose_name = _(u"package")
        verbose_name_plural = _(u"packages")
        get_latest_by = "releases__latest"
        ordering = ['name',]

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('djangopypi2-package', (), {'package_name': self.name})

    @property
    def latest(self):
        try:
            return self.releases.latest()
        except Release.DoesNotExist:
            return None

    def get_release(self, version):
        """Return the release object for version, or None"""
        try:
            return self.releases.get(version=version)
        except Release.DoesNotExist:
            return None

    @staticmethod
    def simple_search(query = ""):
        return Package.objects.filter(Q(name__icontains=query) | Q(releases__package_info__icontains=query)).distinct()

    @staticmethod
    def advanced_search(name = "", summary = "", description = "", classifier = None, keyword = None):
        classifier = classifier if classifier is not None else set()
        keyword = keyword if keyword is not None else set()

        qset = Package.objects.all()
        if name:
            qset = qset.filter(name__icontains = name)

        # manual filtering
        evaled = False
        if summary:
            if not evaled:
                qset = list(qset)
            evaled = True
            qset = filter(lambda x: all(y in x.latest.summary.lower() for y in summary.lower().split()), qset)
        if description:
            if not evaled:
                qset = list(qset)
            evaled = True
            qset = filter(lambda x: all(y in x.latest.description.lower() for y in description.lower().split()), qset)
        if classifier:
            classifier = set(unicode(x) for x in classifier)
            if not evaled:
                qset = list(qset)
            evaled = True
            qset = filter(lambda x: set(x.latest.classifiers) & classifier == classifier, qset)
        if keyword:
            keyword = set(kword.lower() for kword in keyword)
            if not evaled:
                qset = list(qset)
            evaled = True
            qset = filter(lambda x: set(y.lower() for y in x.latest.keywords) & keyword == keyword, qset)

        if not evaled:
            result = list(qset)
        else:
            result = qset
        return result

class Release(models.Model):
    package = models.ForeignKey(Package, related_name="releases", editable=False)
    version = models.CharField(max_length=128, editable=False)
    metadata_version = models.CharField(max_length=64, default='1.0')
    package_info = PackageInfoField(blank=False)
    hidden = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = _(u"release")
        verbose_name_plural = _(u"releases")
        unique_together = ("package", "version")
        get_latest_by = 'created'
        ordering = ['-created']

    def __unicode__(self):
        return self.release_name

    @property
    def release_name(self):
        return u"%s-%s" % (self.package.name, self.version)

    @property
    def summary(self):
        return self.package_info.get('summary', u'')

    @property
    def author(self):
        return self.package_info.get('author', u'')

    @property
    def home_page(self):
        return self.package_info.get('home_page', u'')

    @property
    def license(self):
        return self.package_info.get('license', u'')

    @property
    def description(self):
        return self.package_info.get('description', u'')

    @property
    def classifiers(self):
        return self.package_info.getlist('classifier')

    @property
    def keywords(self):
        # return keywords as set
        keywords = self.package_info.getlist('keywords')
        if keywords:
            return set(self.package_info.getlist('keywords')[0].split())
        else:
            return set()

    @models.permalink
    def get_absolute_url(self):
        return ('djangopypi2-release', (), {'package_name': self.package.name,
                                            'version': self.version})
    @staticmethod
    def simple_search(name = "", summary = ""):
        return Release.objects.filter(Q(package__name__icontains=name) | Q(package_info__icontains=summary)).distinct()

def distribution_upload_path(instance, filename):
    configuration = Configuration.objects.latest()
    return os.path.join(str(configuration.upload_directory), filename)

class Distribution(models.Model):
    release = models.ForeignKey(Release, related_name="distributions",
                                editable=False)
    content = models.FileField(upload_to=distribution_upload_path)
    md5_digest = models.CharField(max_length=32, blank=True, editable=False)
    filetype = models.ForeignKey(DistributionType, related_name='distributions')
    pyversion = models.ForeignKey(PythonVersion, related_name='distributions', null=True,
                                  help_text='Python version, or None for any version of Python')
    platform = models.ForeignKey(PlatformName, related_name='distributions', null=True,
                                 help_text='Platform name or None if platform agnostic')
    comment = models.CharField(max_length=255, blank=True)
    signature = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    uploader = models.ForeignKey(User, related_name='distributions_uploaded',
                                 editable=False, blank=True, null=True)

    @property
    def filename(self):
        return os.path.basename(self.content.name)

    @property
    def display_filetype(self):
        return self.filetype.name

    @property
    def path(self):
        return self.content.name

    def get_absolute_url(self):
        return "%s#md5=%s" % (self.content.url, self.md5_digest)

    class Meta:
        verbose_name = _(u"distribution")
        verbose_name_plural = _(u"distributions")
        unique_together = ("release", "filetype", "pyversion", "platform")

    def __unicode__(self):
        return self.filename


@receiver(post_delete, sender=Distribution)
def handle_media_delete(instance, **kwargs):
    path = os.path.join(settings.MEDIA_ROOT, instance.path)
    log.info("Deleting file {}".format(path))
    os.remove(path)

class Review(models.Model):
    release = models.ForeignKey(Release, related_name="reviews")
    rating = models.PositiveSmallIntegerField(blank=True)

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_confirm_delete.html
{% extends 'pypi_packages/base.html' %}

{% block title %}Delete {{ package }}{% endblock %}

{% block content %}
<h1>Delete {{ package }}</h1>

<p>
  You are about to delete {{ package }}.
</p>

<div class="alert alert-error">
  This will delete the package and any uploaded file it contains.<br>
  <b>Once deleted, this cannot be undone.</b>
</div>

<p>
  Are you sure you want to delete {{ package }}?
</p>

<form method="post">
  <div class="form-actions">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete this package</button>
    <a href="{{ package.get_absolute_url }}" class="btn">No, go back</a>
  </div>
</form>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_detail.html
{% extends 'pypi_packages/base.html' %}
{% load safemarkup %}
{% load static %}

{% block title %}{{ package.name }}{% endblock %}
{% block extra_head %}
<link rel="meta" title="DOAP" type="application/rdf+xml" href="{% url 'djangopypi2-pypi-package-doap' package_name=package.name %}">
{% endblock %}

{% block content %}
<h1>
  {{ package }}
  <div class="btn-group pull-right">
    <button class="btn dropdown-toggle" data-toggle="dropdown">More <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li>
        <a href="{% url 'djangopypi2-pypi-package-doap' package_name=package.name %}"><i class="icon-tags">&nbsp;</i> DOAP XML</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="divider"></li>
      <li>
        <a href="{% url 'djangopypi2-package-permission' package_name=package.name %}"><i class="icon-check">&nbsp;</i> Manage Permission</a>
      </li>
      <li class="divider"></li>
      <li>
        <a href="{% url 'djangopypi2-package-delete' package_name=package.name %}"><i class="icon-trash">&nbsp;</i> Delete</a>
      </li>
      {% endif %}
    </ul>
  </div>
</h1>

{% if not package.latest %}
<div>No releases yet!</div>
{% else %}

<div class="well well-small">
  {% with package.latest as release %}
  {% if release.description %}
  {{ release.description|saferst }}
  {% else %}
  <i>This package has no description</i>
  {% endif %}
  {% endwith %}
</div>

<table class="table table-striped">
  <thead>
    <th>Version</th>
    <th>Downloads</th>
    <th>First Created</th>
  </thead>
  {% for release in package.releases.all %}
  <tr>
    <td><a href="{{ release.get_absolute_url }}">Version {{ release.version }}</a></td>
    <td>{{ release.distributions.count }}</td>
    <td>{{ release.created }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_list.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Package Index{% endblock %}
{% block content %}
<h1 class="pull-left">Package Index</h1>

<form class="navbar-search pull-right">
    {% for field in search_form %}
        {{ field }}
    {% endfor %}
    <div class="btn-group">
        <label for="mySubmit" class="btn"><i class="icon-search"></i></label>
        <input id="mySubmit" type="submit" value="Submit" class="hidden" />

        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="{% url 'djangopypi2-packages-search' %}">Advanced Search</a>
        </ul>
    </div>

</form>

<table class="table table-striped table-condensed table-bordered">
  <thead>
    <th>Package</th>
    <th>Latest version</th>
    <th>Released</th>
  </thead>

  <tbody>
    {% for package in packages %}
    <tr>
      <td>
        <a href="{{ package.get_absolute_url }}">{{ package.name }}</a>
      </td>
      <td>
        {% if package.latest %}{{ package.latest.version }}{% endif %}
      </td>
      <td>
        {% if package.latest %}{{ package.latest.created|timesince }} ago{% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_manage.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Manage {{ package.name }}{% endblock %}
{% block body %}
<h1>Manage {{ package.name }}</h1>
<div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</div>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_manage_versions.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Manage {{ package.name }} Versions{% endblock %}
{% block content %}
<h1>Manage {{ package.name }} Versions</h1>
<form action="" method="post">
{% csrf_token %}
{{ formset.management_form }}
<table>
    <thead>
        <tr>
            <th>Remove?</th>
            <th>Version</th>
            <th>Hide?</th>
            <th colspan="3">Links</th>
        </tr>
    </thead>
    <tbody>
    {% for form in formset.forms %}
        {% for field in form %}{% if field.is_hidden %}{{ field }}{% endif %}{% endfor %}
        {% with form.instance as release %}
        <tr>
            <td>{{ form.DELETE }}</td>
            <td>{{ release.version }}</td>
            <td>{{ form.hidden }}</td>
            <td><a href="{% url 'djangopypi2-release' package=release.package.pk version=release.version %}">Show</a></td>
            <td><a href="{% url 'djangopypi2-release-manage-metadata' package=release.package.pk version=release.version %}">Edit</a></td>
            <td><a href="{% url 'djangopypi2-release-manage-files' package=release.package.pk version=release.version %}">Files</a></td>
        </tr>
        {% endwith %}
    {% endfor %}
    </tbody>
</table>
<div><input type="submit" value="Save" /></div>
</form>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_permission.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Package Permission{% endblock %}

{% block extra_head %}
<script>
    $(function() {
        function updatePermission(action, relation, username, onSuccess, onFail) {
            $.post("{% url 'djangopypi2-package-permission' package_name=package.name %}", {
                "username": username,
                "relation": relation,
                "action": action,
                "csrfmiddlewaretoken": "{{csrf_token}}"
            }).done(onSuccess).fail(onFail);
        }

        function addRow(parent, username) {
            var rowHTML = [
                '<tr>',
                    '<td>',
                        username,
                    '</td>',
                    '<td>',
                        '<button type="button" class="btn btn-small btn-danger" value="' + username + '" action="delete">Delete</button>',
                        '<span class="label label-warning"></span>',
                    '</td>',
                '</tr>'
            ].join("\n");
            parent.append(rowHTML);
        }

        function saveRelation(buttonDOM, relationType) {
            var username = $("#" + buttonDOM.attr("content")).val();
            var success = function() {
                buttonDOM.parents("tr[type='newRow']").remove();
                if(relationType === 'owner') {
                    var tbody = $("#owners-body");
                }
                else if(relationType === 'maintainer') {
                    var tbody = $("#maintainers-body");
                }
                addRow(tbody, username);
            }
            var fail = function() {
                buttonDOM.next().html("Addition failed!");
            }
            updatePermission("add", relationType, username, success, fail);
        }
        $("#owners").delegate("button[action='add']", "click", function() {
            saveRelation($(this), "owner");
        });
        $("#maintainers").delegate("button[action='add']", "click", function() {
            saveRelation($(this), "maintainer");
        });

        function formSubmitEvent(formDOM, event) {
            // Suppress form submit and generate click event instead
            event.preventDefault();
            var buttonDOM = formDOM.closest("tr").find("button[action='add']");
            buttonDOM.click();
        }
        $("#owners").delegate("form[action='add']", "submit", function(e) {
            formSubmitEvent($(this), e);
        });
        $("#maintainers").delegate("form[action='add']", "submit", function(e) {
            formSubmitEvent($(this), e);
        });


        function deleteRelation(buttonDOM, relationType, username) {
            var username = buttonDOM.attr("value");
            var parent = buttonDOM.closest("tr");
            var success = function() {
                parent.remove();
            }
            var fail = function() {
                buttonDOM.next().html("Deletion failed!");
            }
            updatePermission("delete", relationType, username, success, fail);
        }
        $("#owners").delegate("button[action='delete']", "click", function() {
            deleteRelation($(this), "owner");
        });
        $("#maintainers").delegate("button[action='delete']", "click", function() {
            deleteRelation($(this), "maintainer");
        });

        function addEmptyRow(parentTBody) {
            //ID must begin with letters
            var randomId = "id" + Math.random().toString().substring(2);
            var newRow = [
                '<tr type="newRow">',
                    '<td width="80%">',
                        '<form action="add" style="margin: 0 0 0">',
                            '<input type="text" id="' + randomId + '" placeholder="Username">',
                        '</form>',
                    '</td>',
                    '<td>',
                        '<button type="button" class="btn btn-small btn-success" action="add" content="' + randomId + '">Save</button>',
                        '<span class="label label-warning"></span>',
                    '</td>',
                '</tr>'
            ].join("\n");
            parentTBody.append(newRow);
        }
        $("#add-owner").on("click", function() {
            addEmptyRow($("#owners-body"));
        });
        $("#add-maintainer").on("click", function() {
            addEmptyRow($("#maintainers-body"));
        });

        // Initialize table data
        {% for owner in package.owners.all %}
            addRow($("#owners-body"), "{{ owner.username }}");
        {% endfor %}
        {% for maintainer in package.maintainers.all %}
            addRow($("#maintainers-body"), "{{ maintainer.username }}");
        {% endfor %}
    });
</script>
{% endblock %}

{% block content %}
<h2>{{ package.name }} Package Permission</h2>

<h3>Package Owners</h3> 
<table id="owners" class="table table-striped table-condensed table-bordered">
    <thead>
        <th width="80%">Owner</th>
        <th>Action</th>
    </thead>

    <tbody id="owners-body">
    </tbody>
</table>
<button id="add-owner" type="button" class="btn btn-primary">Add Owner</button>

<p>&nbsp;</p>

<h3>Package Maintainers</h3> 
<table id="maintainers" class="table table-striped table-condensed table-bordered">
    <thead>
        <th width="80%">Maintainer</th>
        <th>Action</th>
    </thead>

    <tbody id="maintainers-body">
    </tbody>
</table>
<button id="add-maintainer" type="button" class="btn btn-primary">Add Maintainer</button>

<p>&nbsp;</p>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/package_search.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Advanced Package Search{% endblock %}

{% block content %}

{% if search_result != None %}
<h2>Search Result</h2>
    {% if search_result %}
    <table class="table table-striped table-condensed table-bordered">
      <thead>
        <th>Package</th>
        <th>Summary</th>
      </thead>

      <tbody>
        {% for package in search_result %}
        <tr>
          <td>
            <a href="{{ package.get_absolute_url }}">{{ package.name }}</a>
          </td>
          <td>
            {{ package.latest.summary }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="hero-unit">
        <p>No matching packages found</p>
    </div>
    {% endif %}
{% endif %}

<div class="hero-unit">
    <h2>Advanced Package Search</h2> 
    <form method="post" class="form-horizontal">
        {% csrf_token %}

        {% for field in search_form %}
        <div class="control-group">
            <label class="control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
            <div class="controls">
                {{ field }} <label class="help-inline">{{ field.help_text }}</span>
            </div>
        </div>
        {% endfor %}

        <div class="form-actions">
            <input type="submit" value="Search" class="btn btn-primary">
        </div>
    </form>
</div>



{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/release_confirm_delete.html
{% extends 'pypi_packages/base.html' %}

{% block title %}Delete {{ release }}{% endblock %}

{% block content %}
<h1>Delete {{ release }}</h1>

<p>
  You are about to delete {{ release }}.
</p>

<div class="alert alert-error">
  This will delete the package and any uploaded file it contains.<br>
  <b>Once deleted, this cannot be undone.</b>
</div>

<p>
  Are you sure you want to delete {{ release }}?
</p>

<form method="post">
  <div class="form-actions">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete this release</button>
    <a href="{{ release.get_absolute_url }}" class="btn">No, go back</a>
  </div>
</form>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/release_list.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Releases - Django PYPI{% endblock %}
{% block content %}
<h1>Package Releases</h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Updated</th><th>Package</th><th>Description</th>
    </tr>
  </thead>

  <tbody>
    {% for release in release_list %}
    <tr>
      <td>{{ release.created|date:"Y-m-d" }}
      <td>
        <a href="{{ release.get_absolute_url }}">{{ release }}</a>
      </td>
      <td>{{ release.summary|truncatewords:10 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/release_manage.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Manage {{ release }}{% endblock %}
{% block content %}
<h1>Manage {{ release }}</h1>
<div>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/release_manage_files.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Manage {{ release }} Files{% endblock %}
{% block content %}
<h1>Manage {{ release }} Files</h1>
{% if formset.forms %}
<form action="" method="post">
{% csrf_token %}
{{ formset.management_form }}
<table class="table table-striped">
  <thead>
    <tr>
      <th>Remove?</th>
      <th>Type</th>
      <th>Py Version</th>
      <th>Comment</th>
      <th>Download</th>
      <th>Size</th>
      <th>MD5 Digest</th>
    </tr>
  </thead>

  <tbody>
    {% for form in formset.forms %}
    {% for field in form %}{% if field.is_hidden %}{{ field }}{% endif %}{% endfor %}
    {% with form.instance as dist %}
    <tr>
      <td>{{ form.DELETE }}</td>
      <td>{{ dist.get_filetype_display }}</td>
      <td>{{ dist.pyversion }}</td>
      <td>{{ form.comment }}</td>
      <td><a href="{{ dist.get_absolute_url }}">{{ dist.filename }}</a></td>
      <td>{{ dist.content.size|filesizeformat }}</td>
      <td>{{ dist.md5_digest }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
  </tbody>
</table>

<div>
  <input type="submit" value="Save">
</div>
</form>
{% endif %}
{% if upload_form %}
<h2>Upload a Distribution</h2>
<form action="{% url 'djangopypi2-release-upload-file' package_name=release.package.name version=release.version %}"
    method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ upload_form.as_p }}
    <div><input type="submit" value="Upload"></div>
</form>
{% endif %}
{% endblock %}

djangopypi2/apps/pypi_packages/templates/pypi_packages/release_upload_file.html
{% extends 'pypi_packages/base.html' %}
{% block title %}Manage {{ release }} Files{% endblock %}
{% block content %}
<h1>Upload a File to {{ release }}</h1>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div><input type="submit" value="Upload" /></div>
</form>
{% endblock %}